version: "3.6"

services:
# InternetUp - an ISP health check tool
  internet-up:
    container_name: internet-up
    image: internet-up:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/apps/internetup/config:/data 
    environment:
      - TZ=$TZ
    restart: unless-stopped

  internet-up-dash:
    container_name: internet-up-dash
    image: internet-up-dash:latest
    ports:
      - 80:8050
    volumes:
      - $DOCKERDIR/apps/internetup/config:/data 
    environment:
      - TZ=$TZ
    restart: unless-stopped